name: build-and-test

on: [push]

jobs:
  test: cargo build and test
  runs-on: ubuntu-latest
   strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
  steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - run:  cargo build
    - run:  cargo test --all-features

